name: Pull Request Workflow

on:
  pull_request:
    # Trigger on any pull request, not just on the main branch
    branches:
      - '*'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    if: '! github.event.pull_request.draft'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop -c .rubocop.yml -f progress

  rspec:
    runs-on: ubuntu-latest
    if: '! github.event.pull_request.draft'
    timeout-minutes: 20
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    env:
      RAILS_ENV: test
      GEMFILE_RUBY_VERSION: 3.1.0
      PGHOST: localhost
      DB_USERNAME: postgres
      BASE_URL: 'localhost'
      ALLOWED_DOMAIN: *
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      - name: Install libvips
        run: sudo apt-get update && sudo apt-get install -y libvips
      - name: Create DB
        run: |
          bin/rails db:create db:migrate
      - name: Run tests
        run: |
          bundle exec rspec spec
